name: build

on:
  workflow_dispatch:
  schedule:
    - cron: '17 1 * * *'

jobs:
  build_noetic:
    runs-on: ubuntu-22.04
    steps:
      - uses: jspricke/ros-deb-builder-action@main
        with:
          DEB_DISTRO: focal
          ROS_DISTRO: noetic
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SQUASH_HISTORY: true
